version: 2.1

orbs:
  helm: circleci/helm@3
  commitlint: conventional-changelog/commitlint@1.0

executors:
  k8s:
    docker:
      - image: alpine/k8s:1.28.14
    resource_class: small
  node:
    docker:
      - image: cimg/node:lts
    resource_class: small

commands:
  install-chart-releaser:
    parameters:
      cr-version:
        type: string
        default: "1.7.0"
    steps:
      - restore_cache:
          key: chart-releaser-<<parameters.cr-version>>
      - run:
          name: install chart-releaser
          command: |
            if [[ ! -f cr.tar.gz ]]; then
              curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v<<parameters.cr-version>>/chart-releaser_<<parameters.cr-version>>_linux_amd64.tar.gz"
            fi
            tar -xzvf cr.tar.gz cr
            sudo mv cr /usr/local/bin/cr
            cr version
      - save_cache:
          paths:
            - cr.tar.gz
          key: chart-releaser-<<parameters.cr-version>>

jobs:
  unittest:
    executor: k8s
    steps:
      - checkout
      - run:
          name: helm unittest
          command: helm unittest charts/snyk-broker

  publish:
    executor: node
    steps:
      - checkout
      - helm/install_helm_client
      - install-chart-releaser
      - run:
          name: install semantic-release and plugins
          command: sudo npm ci
      - run:
          # this is required by chart-releaser
          name: ensure that git uses https origin
          command: |
            git config url."https://github.com/".insteadOf "git@github.com:"
            git remote get-url --push origin
      - run:
          name: publish
          command: npx semantic-release

workflows:
  validate_and_publish:
    jobs:
      - unittest
      - publish:
          context:
            - team-hybrid-common
          filters:
            branches:
              only:
                - main
